import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Main from "../data/main";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rarest Society</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Main />
    </div>
  );
}
